name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t my-node-app .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.Docker_Hub_Username }}
        password: ${{ secrets.Docker_Hub_Password }}
    - name: Push the Docker image
      run: |
        docker tag my-node-app ${{ secrets.Docker_Hub_Username }}/my-node-app
        docker push ${{ secrets.Docker_Hub_Username}}/my-node-app
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.Docker_Hub_Username }}/my-node-app
          docker stop my-node-app || true
          docker rm my-node-app || true
          docker run -d --name my-node-app -p 80:3000 ${{ secrets.Docker_Hub_Username }}/my-node-app
        docker push my-node-app -p 80:3000 ${{ secrets.Docker_Hub_Username }}/my-node-app
